apiVersion: v1
kind: Service
metadata:
  name: banking-ip-service
  namespace: backend
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
      protocol: TCP
      name: banking-api
  selector:
    component: bank
